import Viewer from '../src/nucleus';

// Generated by CoffeeScript 1.10.0
describe('Test of nucleus.coffee', function() {
  let elements = null;
  beforeEach(function() {
    elements = [null, null, null];
    let results = [];
    for (let i in elements) {
      elements[i] = window.document.createElement('section');
      elements[i].innerHTML = '<animation>' +
                              '  <keyframe target="h1"></keyframe>' +
                              '  <keyframe target="h2"></keyframe>' +
                              '</animation>';
      results.push(window.document.body.appendChild(elements[i]));
    }
  });

  afterEach(function() {
    for (let i in elements) {
      window.document.body.removeChild(elements[i]);
    }
    elements = null;
  });

  it('skips to aspecified page', function() {
    let nucleus = Libretto.nucleus();
    nucleus.skipTo(2);
    expect(nucleus.getPageIndex()).to.equal(2);
  });

  it('fires a keyframe if the page has keyframes', function() {
    let nucleus = Libretto.nucleus();
    let element = elements[0];
    nucleus.skipTo(0);
    expect(nucleus.nextKeyframe).to.equal(element.querySelectorAll('keyframe')[0]);
    nucleus.step();
    expect(nucleus.nextKeyframe).to.equal(element.querySelectorAll('keyframe')[1]);
    nucleus.step();
    expect(nucleus.nextKeyframe).to.be.null;
  });

  it('moves to a next page if the page has no-keyframes', function() {
    let nucleus = Libretto.nucleus();
    nucleus.skipTo(1);
    nucleus.step();
    nucleus.step();
    nucleus.step();
    expect(nucleus.nextKeyframe).to.equal(elements[2].querySelector('keyframe'));
  });

  it('skips to aspecified page', function() {
    let nucleus = Libretto.nucleus();
    nucleus.skipTo(2);
    expect(nucleus.getPageIndex()).to.equal(2);
  });

  it('skips to next page', function() {
    let nucleus = Libretto.nucleus();
    nucleus.skipTo(1);
    nucleus.skipNext();
    expect(nucleus.getPageIndex()).to.equal(2);
  });

  it('skips to previous page', function() {
    let nucleus = Libretto.nucleus();
    nucleus.skipTo(1);
    nucleus.skipPrev();
    expect(nucleus.getPageIndex()).to.equal(0);
  });
});
