// Generated by CoffeeScript 1.10.0
describe('Test of page.coffee', function() {
  let elements = null;
  beforeEach(function() {
    elements = [null, null, null];
    let results = [];
    for (let i in elements) {
      elements[i] = window.document.createElement('section');
      results.push(window.document.body.appendChild(elements[i]));
    }
    results;
  });

  afterEach(function() {
    for (let ele of elements) {
      window.document.body.removeChild(ele);
    }
    elements = null;
  });

  it('returns the number of the page which has body as parent', function() {
    let grandchildElement = document.createElement('section');
    elements[1].appendChild(grandchildElement);
    expect(Libretto.Page.count()).to.equal(3);
  });

  it('returns a page object of the specified by index', function() {
    let grandchildElement = document.createElement('section');
    elements[1].appendChild(grandchildElement);
    let object = Libretto.Page.pageAt(2);
    let childSections = [];
    for (let child of Array.prototype.slice.call(window.document.body.children)) {
      if (child.tagName.match(/section/i)) {
        childSections.push(child);
      }
    }
    expect(object.element).to.equal(childSections[2]);
  });

  it('returns an index of the pages', function() {
    let grandchildElement = document.createElement('section');
    expect(Libretto.Page.pageAt(1).indexOf()).to.equal(1);
  });

  it('returns an effect name if the name is given', function() {
    let pageEle = window.document.body.getElementsByTagName('section')[1];
    pageEle.setAttribute('effect', 'my_effect');
    let page = Libretto.Page.pageAt(1);
    expect(page.animationEffect()).to.equal('my_effect');
  });

  it('returns null if the name is not given', function() {
    let pageEle = window.document.body.getElementsByTagName('section')[1];
    let page = Libretto.Page.pageAt(1);
    expect(page.animationEffect()).to.be["null"];
  });

  it('a effect duration if the duration is given', function() {
    let pageEle = window.document.body.getElementsByTagName('section')[1];
    pageEle.setAttribute('duration', '500ms');
    let page = Libretto.Page.pageAt(1);
    expect(page.animationDuration()).to.equal('500ms');
  });

  it('null if the duration is not given', function() {
    let pageEle = window.document.body.getElementsByTagName('section')[1];
    let page = Libretto.Page.pageAt(1);
    expect(page.animationDuration()).to.be["null"];
  });
});
