import Page from '../src/page';
import PageTransition from '../src/page_transition';

// Generated by CoffeeScript 1.10.0
describe('Test of page_transition.coffee', function() {
  beforeEach(function() {
    this.pageEle1 = window.document.createElement('section');
    this.pageEle2 = window.document.createElement('section');
    this.pageEle1.style.position = 'absolute';
    this.pageEle2.style.position = 'absolute';
    window.document.body.appendChild(this.pageEle1);
    window.document.body.appendChild(this.pageEle2);
    this.prevPage = new Page(this.pageEle1);
    this.nextPage = new Page(this.pageEle2);
  });

  afterEach(function() {
    window.document.body.removeChild(this.pageEle1);
    window.document.body.removeChild(this.pageEle2);
    this.prevPage = null;
    this.nextPage = null;
    this.pageEle1 = null;
    this.pageEle2 = null;
  });

  it('constructs and destructs a object', function() {
    let pageTransition = new PageTransition(0, 1, this.nextPage, 'TestPageTransition');
    let styleEle = window.document.getElementById('TestPageTransition');
    expect(styleEle).not.to.be.null;
    pageTransition.finalize();
    styleEle = window.document.getElementById('TestPageTransition');
    expect(styleEle).to.be.null;
  });

  it('switches the page without transition', function() {
    let pageTransition = new PageTransition(0, 1, this.nextPage, 'TestPageTransition');
    pageTransition.switchPage(false);
    expect(window.getComputedStyle(this.pageEle1).zIndex).to.be.below(window.getComputedStyle(this.pageEle2).zIndex);
    pageTransition.finalize();
  });
  xit('switches the page with transition', function() {});
});
