// Generated by CoffeeScript 1.10.0
Libretto.Plugin = (function() {
  function Plugin(name) {
    window.addEventListener("load", this.initialize);
  }

  Plugin.prototype.initialize = function() {};

  return Plugin;

})();
